In [69]:
import tensorflow as tf


In [70]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1.0, seed=1421)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.5378824e+00, -3.9098343e-01, -7.6787031e-01, -1.7393292e-01,
         1.7150328e+00],
       [ 4.1712043e-01,  9.7181523e-01,  6.4957571e-01, -1.3726435e+00,
        -1.6776335e+00],
       [-5.5602286e-02, -1.2650486e+00,  1.6875717e-01,  9.9819887e-01,
         1.3863436e+00],
       [-2.3242867e+00,  2.2864642e+00,  2.4255076e-01,  1.1581496e-03,
        -8.6332768e-01],
       [ 1.2785087e+00,  4.5997176e-02, -1.4320582e+00,  2.0788594e-01,
        -1.5848538e-01]], dtype=float32)>

In [71]:
list_prima = [[2, 3, 5, 7, 11], [13, 17, 19, 23, 29], [31, 37, 41, 43, 47], [53, 59, 61, 67, 71], [73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(list_prima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

In [72]:
dimensi_random = random_tensor.get_shape()
dimensi_prima = prime_tensor.get_shape()

print("Dimensi variable random : ", dimensi_random)
print("Dimensi variable prima  : ", dimensi_prima)

Dimensi variable random :  (5, 5)
Dimensi variable prima  :  (5, 5)


In [73]:
add = tf.add(random_tensor, prime_tensor).numpy()
subtract = tf.subtract(random_tensor, prime_tensor).numpy()
multiply = tf.multiply(random_tensor, prime_tensor).numpy()
divide = tf.divide(random_tensor, prime_tensor).numpy()
power = tf.pow(random_tensor, prime_tensor).numpy()


print("Operator Penjumlahan dari variable random dan prime")
print(add)

print("\nOperator Pengurangan dari variable random dan prime")
print(subtract)

print("\nOperator Perkalian dari variable random dan prime")
print(multiply)

print("\nOperator Pembagian dari variable random dan prime")
print(divide)

print("\nOperator Perpangkatan dari variable random dan prime")
print(power)

Operator Penjumlahan dari variable random dan prime
[[ 0.46211755  2.6090167   4.2321296   6.826067   12.715033  ]
 [13.41712    17.971815   19.649576   21.627357   27.322367  ]
 [30.944397   35.73495    41.16876    43.9982     48.386345  ]
 [50.675713   61.286465   61.24255    67.00116    70.13667   ]
 [74.27851    79.046      81.56794    89.207886   96.841515  ]]

Operator Pengurangan dari variable random dan prime
[[ -3.5378823  -3.3909833  -5.7678704  -7.173933   -9.284967 ]
 [-12.58288   -16.028185  -18.350424  -24.372643  -30.677633 ]
 [-31.055603  -38.26505   -40.83124   -42.0018    -45.613655 ]
 [-55.324287  -56.713535  -60.75745   -66.99884   -71.86333  ]
 [-71.72149   -78.954     -84.43206   -88.792114  -97.158485 ]]

Operator Perkalian dari variable random dan prime
[[-3.07576489e+00 -1.17295027e+00 -3.83935165e+00 -1.21753049e+00
   1.88653603e+01]
 [ 5.42256546e+00  1.65208588e+01  1.23419380e+01 -3.15708008e+01
  -4.86513710e+01]
 [-1.72367084e+00 -4.68068008e+01  6.91904

In [74]:
random_max_col = tf.argmax(random_tensor, axis = 0)
random_max_row = tf.argmax(random_tensor, axis = 1)
random_min_col = tf.argmin(random_tensor, axis = 0)
random_min_row = tf.argmin(random_tensor, axis = 1)

print("Inputan Tensor : \n",random_tensor.numpy())
print("\n")
print("Lokasi Nilai Max Dari Column", random_max_col.numpy())
print("Lokasi Nilai Max Dari Row", random_max_row.numpy())
print("Lokasi Nilai Min Dari Column", random_min_col.numpy())
print("Lokasi Nilai Min Dari Row", random_min_row.numpy())

Inputan Tensor : 
 [[-1.5378824e+00 -3.9098343e-01 -7.6787031e-01 -1.7393292e-01
   1.7150328e+00]
 [ 4.1712043e-01  9.7181523e-01  6.4957571e-01 -1.3726435e+00
  -1.6776335e+00]
 [-5.5602286e-02 -1.2650486e+00  1.6875717e-01  9.9819887e-01
   1.3863436e+00]
 [-2.3242867e+00  2.2864642e+00  2.4255076e-01  1.1581496e-03
  -8.6332768e-01]
 [ 1.2785087e+00  4.5997176e-02 -1.4320582e+00  2.0788594e-01
  -1.5848538e-01]]


Lokasi Nilai Max Dari Column [4 3 1 2 0]
Lokasi Nilai Max Dari Row [4 1 4 1 0]
Lokasi Nilai Min Dari Column [3 2 4 1 1]
Lokasi Nilai Min Dari Row [0 4 1 0 2]


In [75]:
print("Dimensi variable random tensor : ", dimensi_random)
print("Dimensi variable prime tensor  : ", dimensi_prima)

concate_variable_col = tf.concat([random_tensor, prime_tensor], axis = 0)
concate_variable_row = tf.concat([random_tensor, prime_tensor], axis = 1)

print("\nDimensi setelah digabungkan (Dengan Axis Column)   : ", concate_variable_col.shape)
print("Nilai pengabungan dari variable random dan prime   :\n", concate_variable_col.numpy())

print("\nDimensi setelah digabungkan (Dengan Axis Row)      : ", concate_variable_row.shape)
print("Nilai pengabungan dari variable random dan prime   :\n", concate_variable_row.numpy())

Dimensi variable random tensor :  (5, 5)
Dimensi variable prime tensor  :  (5, 5)

Dimensi setelah digabungkan (Dengan Axis Column)   :  (10, 5)
Nilai pengabungan dari variable random dan prime   :
 [[-1.5378824e+00 -3.9098343e-01 -7.6787031e-01 -1.7393292e-01
   1.7150328e+00]
 [ 4.1712043e-01  9.7181523e-01  6.4957571e-01 -1.3726435e+00
  -1.6776335e+00]
 [-5.5602286e-02 -1.2650486e+00  1.6875717e-01  9.9819887e-01
   1.3863436e+00]
 [-2.3242867e+00  2.2864642e+00  2.4255076e-01  1.1581496e-03
  -8.6332768e-01]
 [ 1.2785087e+00  4.5997176e-02 -1.4320582e+00  2.0788594e-01
  -1.5848538e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]]
